### ISSUE TITLE
Не загружается файл отчета

### ISSUE THREAD

**Issue by theshadowco** [DoublesunRUS/ru.capralow.dt.unit.launcher#10]
Не загружается файл отчета (сам, плагином)

![image](https://user-images.githubusercontent.com/9591731/60240062-740e2800-98b8-11e9-8672-80056c7d7c3e.png)

Текст ошибки: **The test run could not be imported from file 'C:\edt_ws\bsp_edt\ФреймворкТестирования\junit.xml'.**

Стек-трейс 
```

java.io.FileNotFoundException: C:\edt_ws\bsp_edt\ФреймворкТестирования\junit.xml (Не удается найти указанный файл)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
	at org.eclipse.jdt.internal.junit.model.JUnitModel.importTestRunSession(JUnitModel.java:389)
	at org.eclipse.jdt.junit.JUnitCore.importTestRunSession(JUnitCore.java:199)
	at ru.capralow.dt.unit.launcher.plugin.ui.launchconfigurations.UnitTestLaunch.showJUnitResult(UnitTestLaunch.java:38)
	at ru.capralow.dt.unit.launcher.plugin.ui.UnitLauncherManager.handleDebugEvents(UnitLauncherManager.java:34)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1137)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1171)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:444)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

Не смотря на текст ошибки, файл находится именно там (проверил), где он его ищет.

Параметры EDT

```
eclipse.buildId=unknown
java.version=1.8.0_212
java.vendor=BellSoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64

```
EDT: **Topaz 1.11.0.773**

**Comment by theshadowco** [comment]
Проблема похоже ясна - файл с результатом подгружается от предыдущего запуска, т.е. первый раз дает ошибку, т.к. файла еще нет. При повторном запуске, еще до загрузки VA показывает результаты. После выполнения результат не обновляется до следующего перезапуска.

**Comment by theshadowco** [comment]
Проверил и на версии Topaz 1.11.0.869  - аналогично

**Comment by DoublesunRUS** [comment]
Просьба проверить на версии 0.2.0

**Comment by theshadowco** [comment]
увы, даже запустить не удается - 

Произошла ошибка в течение запуска 1С:Предприятия:

```

java.lang.NullPointerException
	at ru.capralow.dt.unit.launcher.plugin.core.frameworks.FrameworkUtils.getTestModules(FrameworkUtils.java:247)
	at ru.capralow.dt.unit.launcher.plugin.core.frameworks.FrameworkUtils.getModuleByName(FrameworkUtils.java:182)
	at ru.capralow.dt.unit.launcher.plugin.core.frameworks.FrameworkUtils.getModuleFromConfiguration(FrameworkUtils.java:200)
	at ru.capralow.dt.internal.launching.core.RuntimeUnitLauncherLaunchDelegate.getFeaturesPath(RuntimeUnitLauncherLaunchDelegate.java:430)
	at ru.capralow.dt.internal.launching.core.RuntimeUnitLauncherLaunchDelegate.parseParamsTemplate(RuntimeUnitLauncherLaunchDelegate.java:591)
	at ru.capralow.dt.internal.launching.core.RuntimeUnitLauncherLaunchDelegate.saveParamsToFile(RuntimeUnitLauncherLaunchDelegate.java:691)
	at ru.capralow.dt.internal.launching.core.RuntimeUnitLauncherLaunchDelegate.doLaunch(RuntimeUnitLauncherLaunchDelegate.java:138)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:55)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by theshadowco** [comment]
и настройки конфигурации "Модульные тесты" после сохранения не редактируются

**Comment by DoublesunRUS** [comment]
Досадная ошибка, которая закралась в последний момент. Поправил.

**Comment by theshadowco** [comment]
Так и не получается, теперь новая ошибка 

```

com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionException: Операция конфигурирования завершена неуспешно
Операция не может быть выполнена, так как расширение конфигурации с указанным именем не найдено: Тест
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:138)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execInDesignerSession(DesignerSessionThickClientLauncher.java:525)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.getChanges(DesignerSessionThickClientLauncher.java:348)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.checkConflict(AbstractInfobaseConnection.java:637)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.IncrementalInfobaseConnection.loadObjects(IncrementalInfobaseConnection.java:115)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadObjects(AbstractInfobaseConnection.java:174)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadObjects(ParticipantAwareInfobaseConnection.java:78)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadObjects(ReconnectableInfobaseConnection.java:119)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:97)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.UpdateInfobase.run(UpdateInfobase.java:92)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com._1c.g5.designer.ssh.client.DesignerClientException: Операция не может быть выполнена, так как расширение конфигурации с указанным именем не найдено: Тест
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.processExecutionResponses(AbstractQuery.java:154)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.execute(AbstractQuery.java:135)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.exec(AbstractQuery.java:86)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractTransferingQuery.runOperation(AbstractTransferingQuery.java:137)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingConfigureQuery.exec(TransferingConfigureQuery.java:59)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingConfigureQuery.exec(TransferingConfigureQuery.java:32)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$9(DesignerSessionThickClientLauncher.java:351)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:78)
	... 10 more
```


![image](https://user-images.githubusercontent.com/9591731/60318761-ecd6b800-997c-11e9-972d-baea392219ca.png)

![image](https://user-images.githubusercontent.com/9591731/60318775-fa8c3d80-997c-11e9-89b7-5aeea7358cb9.png)

**Comment by DoublesunRUS** [comment]
Это уже не ошибка плагина.
Тут нужно разбираться, почему EDT считает что его нет.
Для расширения указан базовый проект? Расширение точно есть в конфигураторе?

**Comment by theshadowco** [comment]
Пересоздал расширение и все заработало!
